# -*- coding: utf-8 -*-
"""Bus_Ticket_Booking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qs-xxBTzvt-8kdwWCFkw5jmRb2Xot7nt
"""

print("Bus Ticket Booking!!")
#start=["Mumbai","Pune","Nashik"]
#stop=["Mumbai","Pune","Nashik"]
passenger=[]
available_seats=20
booked_seats=0
seats=0
cancel_seats=0
while True:
  print("1.Available seats\n2.Book tickets\n3.Cancel tickets\n4.Exit")
  choice=int(input("Enter Your Choice(1-4):"))
  if choice==1:
    start_bus_stop=input("Enter your bus stop:").lower()
    destination=input("Enter your destinaton:").lower()
    if start_bus_stop=="mumbai" and destination=="pune":
      print("BUS NAME:SHIVNERI\nAvailable seats:",available_seats)
    elif start_bus_stop=="mumbai" and destination=="nashik":
       print("BUS NAME:Sahydari Travels\nAvailable seats:",available_seats)
    elif start_bus_stop=="pune" and destination=="mumbai":
       print("BUS NAME:Deccan Rider\nAvailable seats:",available_seats)
    elif start_bus_stop=="pune" and destination=="nashik":
       print("BUS NAME:Western Express\nAvailable seats:",available_seats)
    elif start_bus_stop=="nashik" and destination=="mumbai":
       print("BUS NAME:Nashik Express\nAvailable seats:",available_seats)
    elif start_bus_stop=="nashik" and destination=="pune":
       print("BUS NAME:Pune Rider\nAvailable seats:",available_seats)
    else:
      print("Currently not available!!")
  elif choice==2:
    cost=0
    seats=int(input("Enter Number of seats:"))
    if seats>available_seats:
      print("CURRENTLY NOT AVAILABLE")
      continue
    booked_seats=seats
    while booked_seats>0:
      name=input("Enter Name of Passenger:")
      age=int(input("enter age:"))
      passenger.append([name,age])

      if age<=10:
        cost=cost+100
      elif age>=60:
        cost=cost+150
      else:
        cost=cost+200
      booked_seats=booked_seats-1

    print("Seats booked for:",passenger)
    print("Total Fare:",cost)
    available_seats=available_seats-seats
  elif choice==3:
    cost=0
    present=False
    cancel_seats=int(input("Enter Number of seats to cancel:"))
    while cancel_seats>0:
      name=input("Enter Name of Passenger:")
      age=int(input("enter age:"))
      if [name,age] in passenger:
        passenger.remove([name,age])
        present=True
      else:
        print("PASSENGER NOT FOUND")
      if present:
        available_seats=available_seats+1

        if age<=10:
          cost=cost+100
        elif age>=60:
          cost=cost+150
        else:
          cost=cost+200
        present=False
      cancel_seats=cancel_seats-1
    deduction=0.05*cost
    cost=cost-deduction
    print("According To Rules 5% of total fare has been deducted and total cost to be returned:",cost)
    print("Transaction can take 48hrs")
  elif choice==4:
    break

print(passenger)